# Generated by Django 4.1 on 2022-08-13 23:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Courier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('features', models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='Shipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.FloatField()),
                ('status', models.IntegerField(choices=[(1, 'Ordered'), (2, 'Ready for delivery'), (3, 'Delivered'), (4, 'Cancelled')], default=1)),
                ('price', models.FloatField()),
                ('destination', models.CharField(max_length=256)),
                ('tracking_number', models.CharField(max_length=256)),
                ('courier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shipments', to='couriers.courier')),
            ],
        ),
    ]
